export {
  AuthorIdsSchema,
  ACTIVE_P0_AUTHOR_KEYS,
  normalizeOpenAlexId,
  normalizeOpenAlexBinding,
  allOpenAlexIds,
  mergeOpenAlexIds,
  bindOpenAlexId,
  hasActiveP0AuthorId,
  assertAuthorIdsForLiteratureIngest,
  type AuthorIds,
} from "./author-ids.js";

export {
  HcpTierSchema,
  RoleTagSchema,
  TagMethodSchema,
  HcpTagsSchema,
  FORBIDDEN_TAG_SIGNALS,
  type HcpTier,
  type RoleTag,
  type TagMethod,
  type HcpTags,
} from "./tags.js";

export {
  SCHEMA_VERSION,
  DisambiguationStatusSchema,
  TwinIdentitySchema,
  TwinProfileSchema,
  TwinResearchSchema,
  TwinMetaSchema,
  VirtualTwinSchema,
  UiLocaleSchema,
  DoingNowSchema,
  DoingNowFieldSchema,
  InsightsNarrativeSchema,
  HcpInsightsSchema,
  topLevelNarrative,
  pickInsightsNarrative,
  withInsightsLocale,
  pickResearchThemes,
  assertNoComplianceForbiddenFields,
  type TwinIdentity,
  type VirtualTwin,
  type DoingNow,
  type HcpInsights,
  type InsightsNarrative,
  type UiLocale,
} from "./twin.js";

export {
  McpErrorCodeSchema,
  McpErrorSchema,
  mcpError,
  isMcpError,
  type McpErrorCode,
  type McpError,
} from "./mcp-error.js";

export {
  EngagementRefSchema,
  EngagementOptionSchema,
  GateStatusSchema,
  GateFindingSchema,
  GateResultSchema,
  EngagementOptionsRunSchema,
  ChatModeSchema,
  ChatMessageSchema,
  ChatSessionSchema,
  type EngagementRef,
  type EngagementOption,
  type GateStatus,
  type GateFinding,
  type GateResult,
  type EngagementOptionsRun,
  type ChatMode,
  type ChatMessage,
  type ChatSession,
} from "./engagement.js";
